### ISSUE TITLE
Go macros missing from i686 on ELN

### ISSUE THREAD

**Issue by praiskup** [fedora-eln/eln#80] opened 2021-12-16 14:30 UTC
It is failing with:
```
 Problem 1: cannot install the best candidate for the job
  - nothing provides go-srpm-macros needed by redhat-rpm-config-206-1.eln114.noarch
 Problem 2: package rpm-build-4.17.0-1.eln112.1.i686 requires system-rpm-config, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides go-srpm-macros needed by redhat-rpm-config-206-1.eln114.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
x86_64 is works fine, originally spotted by [mock testsuite](https://github.com/rpm-software-management/mock/pull/827).

**Comment by praiskup** [comment] 2021-12-16 14:31
Is i386 in ELN "EOL", should we drop it from mock-core-configs?

**Comment by fweimer-rh** [comment] 2021-12-16 15:58
I expect that 32-bit applications will not be supportable on the next version of Red Hat Enterprise Linux (the next version after 9, that is). There is the obvious issue that 10+w years of support come rather close to the 2038 cliff. But there could also be an upstream push for implementing the 64-bit time ABI break by default in the next few years, and that ABI change would totally invalidate the reason why having 32-bit libraries (they wouldn't be compatible).

This needs a discussion downstream, I think, and probably in the next year. ELN should then simply reflect those downstream plans.

**Comment by praiskup** [comment] 2021-12-21 09:55
So the question is what to do with `fedora-eln-i386.cfg` in mock.  Should we drop it now?  Seems like
the chroot is already broken, and it only generates build failures (and Copr inherits this problem).

**Comment by fweimer-rh** [comment] 2021-12-21 10:15
Koji is able to create ELN chroots for i686 builds just fine. Surely it's possible to replicate these buildroots outside of mock?

**Comment by praiskup** [comment] 2021-12-21 10:47
It is possible.

So perhaps a better question:  Is the i386 mirroring supposed to work, and will that be fixed?
Or is it just staled, and mock's configuration for i386 should be moved against Koji buildroot:
`baseurl=https://kojipkgs.fedoraproject.org/repos/eln-build/latest/$basearch/`

We already do this for other Fedora configs.

**Comment by praiskup** [comment] 2021-12-21 10:50
Errr.., there's been **no mirroring** in ELN, so far. #33.
Mock uses: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/BaseOS/

**Comment by praiskup** [comment] 2021-12-21 10:58
Wrong again.  We use https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/

So the question is probably if that is going to be fixed (go-srpm-macros provided in i386 subdir), or if
we should adjust the `fedora-eln-i386.cfg` (and how).

**Comment by fweimer-rh** [comment] 2021-12-21 12:01
Ah, so this is likely a Go-specific issue, caused by building with `%{rhel}`. I'll ping some folks.

**Comment by alexsaezm** [comment] 2021-12-21 12:46
@praiskup, may I see what are you doing? I would love to reproduce it locally.

**Comment by praiskup** [comment] 2021-12-21 13:56
Locally reproducible by:
```
$ mock -r fedora-eln-i386 --shell
...
 Problem 1: cannot install the best candidate for the job
  - nothing provides go-srpm-macros needed by redhat-rpm-config-206-1.eln114.noarch
 Problem 2: package rpm-build-4.17.0-1.eln112.1.i686 requires system-rpm-config, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides go-srpm-macros needed by redhat-rpm-config-206-1.eln114.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
The issue is IMO `nothing provides go-srpm-macros needed by redhat-rpm-config-206-1.eln114.noarch`,
while there's no go-srpm-macros in i386 repo.

**Comment by sgallagher** [comment] 2022-01-04 16:25
From [`go-rpm-macros.spec`]():
```
%if 0%{?rhel} >= 9
%global golang_arches   x86_64 aarch64 ppc64le s390x
%endif
```

Golang is not supported on 32-bit x86 on RHEL 9+. The dependency in redhat-rpm-config is the issue; it should be conditional upon the golang arches. I will suggest a patch for discussion.

**Comment by hroncok** [comment] 2022-01-04 16:26
Note that redhat-rpm-config is noarch.

**Comment by sgallagher** [comment] 2022-01-04 16:30
> Note that redhat-rpm-config is noarch.

What do you suggest? Changing it to `Recommends: golang-srpm-macros`?

**Comment by hroncok** [comment] 2022-01-04 16:36
Recommends don't work in the buildroot.

There are several options here. The easiest one I can think of is to build golang-srpm-macros on all architectures even if empty. Another is to add 4 conditional dependencies to redhat-rpm-config, but I kinda don't like defining the list in two places:

```
%if 0%{?rhel}
Requires: (golang-srpm-macros if rpm-build(aarch-64))
Requires: (golang-srpm-macros if rpm-build(ppc-64))
Requires: (golang-srpm-macros if rpm-build(s390-64))
Requires: (golang-srpm-macros if rpm-build(x86-64))
%else
Requires: golang-srpm-macros
%endif
```

**Comment by praiskup** [comment] 2022-01-04 16:47
This is rather problematic:
https://src.fedoraproject.org/rpms/go-rpm-macros/blob/rawhide/f/go-rpm-macros.spec#_128
To make it work, as @hroncok suggests above, I would drop the `BuildArch: noarch` (which appears to be duplicated in the spec file, btw.).

**Comment by sgallagher** [comment] 2022-03-23 13:03
I updated the title of this ticket. I think we need to have a serious conversation about abandoning 32-bit x86 on Fedora ELN. RHEL 9 Beta shipped without i686 support except for limited support for running 32-bit binaries on an x86_64 host.

I think it's worth exploring either doing the same on Fedora ELN or else dropping 32-bit support entirely. The former will be a lot harder, but would keep us more closely aligned with what RHEL 9 is doing. I have to assume (lacking any information otherwise) that the same will be true for RHEL 11.

**Comment by sgallagher** [comment] 2022-03-25 17:24
In today's meeting, we confirmed that we do want to continue carrying 32-bit i686 at least for multilib.

I've submitted a possible fix for the original issue with golang packages at https://src.fedoraproject.org/rpms/go-rpm-macros/pull-request/6 and I'd appreciate a review there.

**Comment by sgallagher** [comment] 2022-04-05 20:00
> Now when you had that conversation, perhaps rename this ticket back to what it is? The original name makes much more sense when reading this. Also, when I say `Fixes https://github.com/fedora-eln/eln/issues/80` in the go-rpm-macros commit, I mean the original ticket, not ELN and 32bit generally.

Sorry for the long delay, I was unavailable last week. I've reviewed your proposed PR and I think that looks like it should do the trick. Thank you for that.

**Comment by hroncok** [comment] 2022-06-06 11:42
After 2 months, my PR to go-rpm-macros was merged, so I submitted builds for Rawhide and ELN.

https://koji.fedoraproject.org/koji/taskinfo?taskID=87938268
https://koji.fedoraproject.org/koji/taskinfo?taskID=87938343

However, ELN i686 fails with:

```
DEBUG util.py:443:  Error: 
DEBUG util.py:443:   Problem: package lorax-templates-rhel-10.0-13.eln115.noarch requires lorax >= 34.9.1, but none of the providers can be installed
DEBUG util.py:443:    - conflicting requests
DEBUG util.py:443:    - nothing provides grub2 needed by lorax-37.5-1.fc37.i686
DEBUG util.py:443:    - nothing provides grub2-tools needed by lorax-37.5-1.fc37.i686
```

No idea why lorax is pulled at all.

**Closed** 2022-06-13 14:51 UTC
Labels: Meeting
